<a href="https://colab.research.google.com/github/HYUNJAE-JEON/HYUNJAE-Python-Exercise/blob/master/1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy 라이브러리를 np라는 이름으로 사용
import numpy as np

## numpy 배열( np.ndarray )

### 1차원 배열

In [ ]:
# np.array(값) - 내가 넣어주는 값으로 ndarray 생성
arr = np.array([1,2,3])
print(type(arr), arr)

<class 'numpy.ndarray'> [1 2 3]


In [ ]:
# 배열.shape - 차원의 크기
# - 숫자의 개수 = 차원의 개수
# - 숫자의 크기 = 차원의 크기
# (3,) - 숫자가 1개 => 1차원 배열
# 숫자가 3 => 1차원인데 크기가 3(data가 3개)
print(arr.shape)

(3,)


In [ ]:
# indexing, slicing 사용 가능
print(arr[0], arr[1], arr[2])

1 2 3


In [ ]:
# 값 수정
# - arr[index] = 값
arr[0] = 5
arr, arr.dtype

(array([5, 2, 3]), dtype('int64'))

In [ ]:
# 전체 데이터를 포함할 수 있는 데이터타입으로
# 설정이 된다.
arr = np.array( [1, 2.1, 3] )
arr, arr.dtype

(array([1. , 2.1, 3. ]), dtype('float64'))

### 2차원 배열

In [ ]:
arr2 = np.array( [[1,2,3],
                  [4,5,6]])

In [ ]:
type(arr2), arr2, arr2.shape
# shape - (2,3)
# 숫자개수 2개 - 2차원배열
# 숫자의 크기가 2와 3
# 행의 크기가 2
# 열의 크기가 3

(numpy.ndarray, array([[1, 2, 3],
        [4, 5, 6]]), (2, 3))

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# indexing, slicing
# arr[행의위치, 열의위치]
print(arr2[0,0], arr2[0,1], arr2[1,0])

1 2 4


In [ ]:
# np.arange(최소값, 최대값(미포함), 간격) - 숫자배열 자동생성
# np.arange(0, 10, 3) - [ 0, 3, 6, 9 ]
arr3 = np.arange(32) # 최소값 자동 0, 간격 자동 1
arr3, arr3.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]), (32,))

In [ ]:
# 배열의 모양 수정
arr3.reshape(4,8) # arr.reshape(행의개수, 열의개수)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
arr3.reshape(2,-1) # 행은 2개, 열은 자동계산

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
arr3.reshape(-1,4) # 열은 4개, 행은 자동계산

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
# 0으로 구성된 배열 생성
a = np.zeros( (2,2) )
a

array([[0., 0.],
       [0., 0.]])

In [ ]:
# 1로 구성된 배열 생성
b = np.ones( (3,3) )
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 내가 원하는 값으로 채워진 배열 생성
# np.full((배열의모양), 채울값)
c = np.full((5,5), -1)
c

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [ ]:
# 항등행렬 - 행, 열의 위치가 같으면 1, 다르면 0
d = np.eye(3) # 행, 열의 개수(무조건 같은크기로생성됨)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.random - 난수발생기

In [ ]:
# random(배열의모양) 
# - 0~1까지 랜덤한 값들로 채워진 배열 생성
e = np.random.random((2,2))
e

array([[0.34129492, 0.22893161],
       [0.60241345, 0.13142909]])

In [ ]:
# 가우시안 정규분포에 맞는 숫자배열 생성
# randn(배열의모양)
f = np.random.randn(30,20)
f

array([[-6.83932077e-02,  4.20474097e-01,  1.07818968e+00,
        -1.13385345e+00,  9.63615420e-02, -1.68253331e-01,
         5.74867687e-02,  1.54338227e-01, -1.32144046e+00,
        -5.68598137e-01,  1.01842266e+00, -6.10409285e-01,
        -3.53982032e-01, -5.16465405e-01, -2.88377055e-01,
         1.23414154e+00, -4.42037439e-01,  5.62800419e-01,
         5.46485100e-01, -1.07466119e+00],
       [-8.12510904e-01,  5.95313137e-02, -1.12414780e+00,
        -1.10428187e-01,  4.39595468e-01, -8.68925014e-01,
         1.88052645e-01, -8.66824892e-01, -3.49776582e-01,
         1.88030028e+00, -3.05308147e-01, -6.73794861e-01,
        -2.04233652e-01, -8.63174793e-01, -1.35171466e+00,
        -7.20508571e-02,  1.62915615e+00, -7.51488413e-02,
        -3.64931254e-01, -1.98891754e-01],
       [ 1.49845356e+00,  1.59071969e-01, -1.29668372e-01,
        -1.90996281e+00,  1.50540969e+00, -3.69306636e-01,
        -7.13522096e-01, -5.06888020e-01, -3.53124321e-01,
         1.58061966e-02,  1.9

In [ ]:
# randint(최소값, 최대값(미포함), 개수)

# 1부터 45까지의 랜덤 정수 18개를 가진 배열 생성 후
# reshape으로 3행 6열로 변경
g = np.random.randint(1,46,18).reshape(3,-1)
g

array([[21, 33, 30, 23, 29, 13],
       [26, 28, 33, 29, 45, 34],
       [36,  9, 44, 13, 19, 34]])

### 인덱싱, 슬라이싱

In [ ]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr, arr.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), (3, 4))

In [ ]:
# arr[행 슬라이싱, 열 슬라이싱]

# 1번행, 모든 열
arr[1,:]

array([5, 6, 7, 8])

In [ ]:
# 슬라이싱 - 차원 유지
# 인덱싱 - 한차원 감소
arr[1:2, :]

array([[5, 6, 7, 8]])

In [ ]:
a[:, 1]

array([0., 0.])

In [ ]:
a[:, 1:2]

array([[0.],
       [0.]])

### fancy indexing

In [ ]:
arr = np.array([[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# arr[ [index1, index2, ..] , [index1, index2, ..] ]
arr[[0,1,2], [0,1,0]]
arr[[0, 2], :]

array([[1, 2],
       [5, 6]])

### boolean indexing(조건 인덱싱)

In [ ]:
arr = np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr >= 5 # 조건설정) 배열의 값이 5 이상인지
# 원본 구조를 유지하면서 조건이 만족되면 True
# 불만족되면 False 값이 할당

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# 조건으로 생성한 boolean 배열을 
# indexing에 그대로 사용하면
# True위치의 데이터만 뽑아내고
# False위치의 데이터는 버린다.
arr[arr >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr[arr >= 10]

array([10, 11, 12])

### 배열의 연산

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [ ]:
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [ ]:
print(x * y)
print(np.multiply(x, y))


[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [ ]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
x + 1
x * 2

array([[2, 4],
       [6, 8]])

In [ ]:
# 제곱근 연산
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
v = np.array([9,10])
w = np.array([11, 12])


In [ ]:
# 내적 함수
# 벡터-벡터, 행렬-벡터, 행렬-행렬
print(v.dot(w))
print(np.dot(v, w))

219
219


In [ ]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [ ]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### 집계함수
- axis : 0 => "모든 행들을 연산"
- axis : 1 => "모든 열들을 연산"

In [ ]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
# np.집계함수(데이터, axis=0 or 1)
# sum, mean, max, min, argmax(최대값의 index)

# axis=0 모든 행들을 연산
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[4 6]
[3 7]


### np.where
#### 조건을 사용해서 값을 변환

In [ ]:
arr = np.random.randn(4,4)
print(arr)

[[ 2.63249063  0.33228478 -0.50431783 -0.02760121]
 [ 0.89407351  0.67787719 -0.01956629  0.81887778]
 [-1.07720175  0.57478519  0.73206225 -0.14267969]
 [-0.58480155  0.1884835   0.7543625   0.81984028]]


In [ ]:
# np.where(조건, 참일때 변환값, 거짓일때 변환값)
print(np.where(arr>0, 1, -1))

[[ 1  1 -1 -1]
 [ 1  1 -1  1]
 [-1  1  1 -1]
 [-1  1  1  1]]


In [ ]:
# 0보다 크면 원본 유지, 크기 않으면 0으로 변환
print(np.where(arr>0, arr, -1))

[[ 2.63249063  0.33228478 -1.         -1.        ]
 [ 0.89407351  0.67787719 -1.          0.81887778]
 [-1.          0.57478519  0.73206225 -1.        ]
 [-1.          0.1884835   0.7543625   0.81984028]]


### 속도 측정
#### 데이터 생성속도

In [ ]:
# python에서 제공하는 랜덤값 생성
from random import normalvariate 
N = 1000

In [ ]:
%timeit [normalvariate(0,1) for _ in range(N)]

1000 loops, best of 3: 683 µs per loop


In [ ]:
%timeit np.random.normal(size=N)

10000 loops, best of 3: 48 µs per loop


#### 연산 속도

In [ ]:
def addList(list1, list2):
  myList = []
  
  for e1, e2 in zip(list1, list2):
    myList.append(e1+e2)

  return myList

In [ ]:
%timeit addList(list(range(5000)),list(range(5000,10000)))

1000 loops, best of 3: 795 µs per loop


In [ ]:
%timeit np.arange(5000)+np.arange(5000,10000)

The slowest run took 24.24 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 16.3 µs per loop
